version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://mongodb:27017/library
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - library-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network

volumes:
  mongodb_data:

networks:
  library-network:
    driver: bridge
